grafana_url: "https://10.185.182.61:30443"
api_token: "hellofromtheenterpriserateam!"
disable_provenance: true
default_folder_uid: "hifromthe3rateam"
json_files:
  - "gpu_alert_temp.json"
  - "gpu_alert_util.json"
  - "gpu_alert_pwr.json"
  - "cpu_temp.json"
  - "cpu_util.json"
  - "tensor_core_util.json"
  - "k8s_kubelet_down.json"
  - "k8s_apiserver_down.json"
  - "k8s_pending_pods.json"
  - "k8s_failed_pods.json"
  - "k8s_node_down.json"
  - "k8s_cpu_namespace.json"
  - "k8s_mem_namespace.json"
    #- "gpu_alert_nvlink_health.json"
    #- "storage_disk_util.json"
    #- "k8s_alert_node_status.json"
    #- "k8s_pods_fail_30_mins.json"
# json_folder: "./my_json_alerts"
